Algoritmo "Comando Para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/06/2025
Var
// Seção de Declarações das variáveis
   contador : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para contador de 1 ate 23 faca
        escreval (contador) //exibe o número
   fimpara


Fimalgoritmo