Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/06/2025
Var
// Seção de Declarações das variáveis 
   nome : caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nome <- "Rogério"

   escreval("Olá ",nome)
   escreva ("Olá ",nome, ", onde você mora?")


Fimalgoritmo