Algoritmo "semnome"
// Mostrar o intervalo que o intervalo definir começando de 1
Var
// Seção de Declarações das variáveis
   numero_final, contador : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite o numero final começando de 1")
   leia (numero_final)
   
   contador <- 1
   
   enquanto contador <= numero_final faca
      escreval (contador)
      contador <- contador + 1
   fimenquanto

Fimalgoritmo