Algoritmo "Saída de dados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Tite
// Descrição    : Exibe mensagens e valores na tela
// Autor(a)     : Rogério
// Data atual   : 04/06/2025
Var
// Seção de Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("Olá, mundo!")     // Exibe: Olá, mundo!
    escreva(10)                 // Exibe: 10 (não precisa de aspas)

Fimalgoritmo
